#!/bin/sh

echo "MYSQL_REPLICA_USER="$MYSQL_REPLICA_USER
echo "MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD
echo "MYSQL_PASSWORD="$MYSQL_PASSWORD

mysql -uroot -p$MYSQL_ROOT_PASSWORD -e" \
CREATE USER '$MYSQL_REPLICA_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; \
GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPLICA_USER'@'%' WITH GRANT OPTION; \
FLUSH PRIVILEGES;
"

#
# do not create replication user by grant at ver.8.0
#
# mysql -uroot -p$MYSQL_ROOT_PASSWORD -e" \
# GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPLICA_USER'@'%' \
# IDENTIFIED BY '$MYSQL_PASSWORD' REQUIRE SSL; \
# "