version: '3.8'
services:
  t015_proxy:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: t015_proxy
    hostname: t015_proxy
    volumes:
       - ./nginx/html:/var/www/html
       - ./nginx/log:/var/log/nginx
       - ./nginx/certs:/tmp/certs
       #- ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./work:/work
    environment:
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
    tty: true
    depends_on:
      - t015_app
    
  t015_app:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: t015_app
    hostname: t015_app
    volumes:
      - ./app:/app
      - ./work:/work
    environment:
      - TZ=${TZ}
    ports:
      - "3001:3001"
    tty: true
    command:
      sh -c "nodemon -L /app/src/webserver.js"
    depends_on:
      - t015_db_master

  t015_db_master:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./db/master/Dockerfile
    container_name: t015_db_master
    hostname: t015_db_master
    volumes:
       - master_data:/var/lib/mysql
       - ./db/master/log:/var/log/mysql
#       - ./master/conf.d: /etc/mysql/conf.d
       - ./db/master/init_data:/docker-entrypoint-initdb.d
       - ./work:/work
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_REPLICA_USER=${DB_REPLICA_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      #- MYSQL_RANDOM_ROOT_PASSWORD: 1
      - TZ=${TZ}
    ports:
      - "3306:3306"
  t015_db_slave:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./db/slave/Dockerfile
    container_name: t015_db_slave
    hostname: t015_db_slave
    volumes:
       - slave_data:/var/lib/mysql
       - ./db/slave/log:/var/log/mysql
#       - ./read/conf.d:/etc/mysql/conf.d
       - ./db/slave/init_data:/docker-entrypoint-initdb.d
       - ./work:/work
    environment:
      - MYSQL_MASTER_HOST=t015_db_master
#      - SOURCE_MYSQL_USER: ${DB_USER}
#      - SOURCE_MYSQL_PASSWORD: ${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_REPLICA_USER=${DB_REPLICA_USER}
      #- MYSQL_RANDOM_ROOT_PASSWORD=1
      - TZ=${TZ}
    depends_on:
      - t015_db_master

volumes:
  master_data:
  slave_data:
